### PR TITLE
feat(remote): use autocomplete search bar \w suggestions API

### PR DESCRIPTION
**Pull request by mirekys**

### CODE REVIEW

**Comment by Ducica** [comment]
When I open the modal, and type something, I get some results back and at the same time I get the "no results" component, which I am not 100% sure is appropriate in this instance
[Screencast from 2024-10-21 11-29-34.webm](https://github.com/user-attachments/assets/9541b1a7-4548-4379-9d80-afff56d99f27)

**Comment by Ducica** [comment]
last thing, but this might be just personal preference, I would add a border to the input, as to me, when it is not focused, it is a bit strange and looks like the "search" button is just hanging in the space.

image

**Comment by mirekys** [comment]
> When I try to add a vocabulary item (a non existing one), I get 500 when I try to save, I am not sure if this issue is related to me.
> 
> Stack res = f(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^ [Screencast from 2024-10-21 11-34-56.webm](https://github.com/user-attachments/assets/23160e3f-4b2e-485a-9d04-9260f3d9772b)
> 
> File "/home/dusanst/Projects/new_nr_docs/nr-docs/.venv/lib/python3.12/site-packages/invenio_drafts_resources/services/records/service.py", line 309, in create res = self._create( ^^^^^^^^^^^^^ File "/home/dusanst/Projects/new_nr_docs/nr-docs/.venv/lib/python3.12/site-packages/invenio_records_resources/services/uow.py", line 380, in inner return f(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/dusanst/Projects/new_nr_docs/nr-docs/.venv/lib/python3.12/site-packages/invenio_records_resources/services/records/service.py", line 355, in _create self.run_components( File "/home/dusanst/Projects/new_nr_docs/nr-docs/.venv/lib/python3.12/site-packages/invenio_records_resources/services/base/service.py", line 72, in run_components getattr(component, action)(*args, **kwargs) File "/home/dusanst/Projects/oarepo-vocabularies/oarepo_vocabularies/authorities/components.py", line 17, in create self.lookup_and_store_authority_records(identity, record) File "/home/dusanst/Projects/oarepo-vocabularies/oarepo_vocabularies/authorities/components.py", line 40, in lookup_and_store_authority_records self.resolve_and_store_authority_record( File "/home/dusanst/Projects/oarepo-vocabularies/oarepo_vocabularies/authorities/components.py", line 76, in resolve_and_store_authority_record raise InvalidRelationError( oarepo_runtime.services.relations.errors.InvalidRelationError: 'External authority failed: '

Current version should redirect you to vocabularies _new page, where you create item as you would normally do, then you can select it like any other vocab item

**Review by Ducica — APPROVED** [review]

**Comment by Ducica** [comment]
@mirekys It looks OK, please just remove the console.logs

**Pull request merged**
