### PR TITLE
feat(remote): VocabularyRemoteSelect component

### PR DESCRIPTION
**Pull request by mirekys**

### CODE REVIEW

**Comment by Ducica** [comment]
Some proptypes issues

image

**Comment by Ducica** [comment]
When I try to add a new item and then, I try to save the draft (this is in context of contributor for example) when press to save the draft I get a 500 and 

 self.resolve_and_store_authority_record(
  File "/home/dusanst/Projects/oarepo-vocabularies/oarepo_vocabularies/authorities/components.py", line 76, in resolve_and_store_authority_record
    raise InvalidRelationError(
oarepo_runtime.services.relations.errors.InvalidRelationError: 'External authority failed: '


Though it is possible I am maybe missing latest version of some dependency. Does it work for you?

image

**Comment by Ducica** [comment]
Small issue with pagination on this pesky screen size

image

**Comment by Ducica** [comment]
I have never seen this error before, though it does not seem to impact the functionality

image
[Screencast from 2024-09-06 15-43-08.webm](https://github.com/user-attachments/assets/ce840785-adf2-461a-9599-70599ea74e00)

**Comment by mirekys** [comment]
> I have never seen this error before, though it does not seem to impact the functionality
> 
> image [Screencast from 2024-09-06 15-43-08.webm](https://github.com/user-attachments/assets/ce840785-adf2-461a-9599-70599ea74e00)

This happens because search apps needs to get exchanged (unmount + mount) when switching from internal APIs to external (ROR) APIs, dunno how to exactly mitigate this yet

**Comment by Ducica** [comment]
Works much better now. Is there some specific reason, why we display the ror:id to the user instead of some human readable thing please? For example, if someone opens a draft and goes to creators, he will see this

image

And it is not possible to know what those things are. Even if you open the modal, you still don't know, because you have not made any api calls to search i.e. the listing does not exist at this point.

**Review by Ducica — APPROVED** [review]

**Review by mesemus — APPROVED** [review]

**Pull request merged**
