### PR TITLE
created VocabularySelect component

### PR DESCRIPTION
**Pull request by Ducica**
Created VocabularySelect component

### CODE REVIEW

**Comment by mirekys** [comment]
Reports "No results found" even if API returns suggestions:

Screenshot 2023-08-07 at 16 42 55

**Comment by Ducica** [comment]
@mirekys Ahoj Miro, for some reason it is necessary to pass search prop like this too

`     <VocabularySelect
              fieldPath="jazyk"
              vocabularyType="languages"
              clearable
              multiple={true}
              search={(options) => options}
            />`

I have found this in invenio's usage 

`

required={false}
--
457 | // Disable UI-side filtering of search results
458 | search={(options) => options}

`
I have to be honest I don't understand it fully, but I guess server side filtering is somehow better and shows more relevant results - maybe you know how it works exactly. Probably after I serialize the items, the front end filtering is unable to match what I am writing to the serialized version of the item.

**Comment by mirekys** [comment]
Hello @Ducica, thanks a lot for a helpful tip! Indeed, Invenio seems to use it basically everywhere in their RelatedSelectInputs, so we solve it by adding as a default value it to our `RelatedSelectField` field. Didn't manage to track down where the issue is, but results from suggestionAPI are already filtered correctly by input's query.

**Comment by mirekys** [comment]
With that fix, this PR looks good to me :)

**Comment by Ducica** [comment]
@mirekys Super, thanks a lot

**Pull request merged**
